### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by babca** [nextgensparx/huawei-router-api#2]
Hi nextgensparx,
I'm unable to run your project.
Could you update the documentation?

```
$ node getTrafficStatistics.js

import router from 'dist/browser.es.js';
       ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

Thank you!

**Comment by nextgensparx** [comment]
It seems you are importing the browser only build but running it from Node.js. Try using `index.es.js` instead of `browser.es.js`. [The bottom of the readme](https://github.com/nextgensparx/huawei-router-api#notes) has more information on the built files.

Additionally, make sure you use `require` instead of import and the `*.cjs.*` build if you plan to use it in Node.js without a build system.

```js
const router = require('dist/index.cjs.js');
```

Please let me know if you have any further issues.

**Comment by babca** [comment]
Thank you for the hint!

This worked for me:

```node
const router = require('./dist/index.cjs.js');
```

when the file `getTrafficStatistics.js` in the project root. Or

```node
const router = require('../dist/index.cjs.js');
```

for the `getTrafficStatistics.js` file in an original location (example folder).

The import error is resolved, but another is there: `UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate`. I applied a quick hack to ignore SSL errors and re-ran, now it doesn't print anything, just waiting indefinitely. I suppose the API of my modem is incompatible as you stated in the other issue/topic.

**Comment by nextgensparx** [comment]
Yes, I don't think it's compatible. 

I guess you will have to make your own library :). Depending on how different the API is, it could be merged into this library. Since I don't own a B2238 I can't really check.
